version: '3'
services:
  service_1:
    build:
      context: ./cont1
    image: cont1
    ports:
    - '80:8080'
    volumes:
    - "/mnt/projectdocker/vol1:/usr/local/tomcat/webapps"
    - "/mnt/logs1:/usr/local/tomcat/logs"

  service_2:
    build:
      context: ./cont2
    image: cont2
    ports:
    - "90:8080"
    volumes:
    - "/mnt/projectdocker/vol2:/usr/local/tomcat/webapps"
    - "/mnt/logs2:/usr/local/tomcat/logs"
